runtime: nodejs22
service: default
handlers:
  # Serve the root URL (/) with secure option
  - url: /
    static_files: dist/index.html
    upload: dist/index.html
  # Serve CSS, JS, images, fonts, and other static assets
  - url: /(.+)\.(.+)
    static_files: dist/\1.\2
    upload: dist/(.+)\.(.+)
  # Serve specific pages based on their URL path (using index.html files)
  - url: /(.*)
    static_files: dist/\1/index.html
    upload: dist/(.*)/index.html
