name: Deploy to Google Cloud App Engine

on:
  push:
    branches:
        - main

jobs:
  deploy:
    if: github.repository == 'PJECZ/pjecz-andromeda-astro'
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          node-version: 22
          package-manager: pnpm@latest
      - name: Authenticate
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy to App Engine
        uses: "google-github-actions/deploy-appengine@v1"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: "app.yaml"
          working_directory: "."
          promote: true
